{% set version = "1.2.3" %}

package:
  name: tableschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tableschema/tableschema-{{ version }}.tar.gz
  sha256: cd709900a3f024ec121239aed569a6df0a2a48dfc9498b86112813066de54f81

build:
  number: 0
  noarch: python
  entry_points:
    - tableschema = tableschema.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click >=3.3,<7.0
    - isodate >=0.5.4,<2.0
    - jsonschema >=2.5,<3.0
    - python-dateutil >=2.4,<3.0
    - requests >=2.5,<3.0
    - rfc3986 >=1.1.0,<2.0
    - six >=1.9,<2.0
    - tabulator >=1.3,<2.0
    - unicodecsv >=0.14,<2.0

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  commands:
    - tableschema --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A utility library for working with Table Schema in Python

extra:
  recipe-maintainers:
    - ocefpaf
