{% set version = "1.15.3" %}

package:
  name: tableschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tableschema/tableschema-{{ version }}.tar.gz
  sha256: 5426ac04ca9dddb47cae24c407857d70f94a7835ed693fbdbb1cc739a0c0f769

build:
  number: 0
  noarch: python
  entry_points:
    - tableschema = tableschema.__main__:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9
    - click >=3.3
    - requests >=2.5
    - python-dateutil >=2.4
    - jsonschema >=2.5
    - unicodecsv >=0.14
    - isodate >=0.5.4
    - rfc3986 >=1.1.0
    - tabulator >=1.20

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  requires:
    - pylama
    - tox
    - pip
  commands:
    - pip check
    - tableschema --help

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A utility library for working with Table Schema in Python

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
