{% set version = "1.7.1" %}

package:
  name: tableschema
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tableschema/tableschema-{{ version }}.tar.gz
  sha256: 64ba58f1654a3bbc5a0d23a2d7d3cb99280932e0095226f3d617c5f83b91666a

build:
  number: 0
  noarch: python
  entry_points:
    - tableschema = tableschema.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9
    - click >=3.3
    - requests >=2.5
    - python-dateutil >=2.4
    - jsonschema >=2.5
    - unicodecsv >=0.14
    - isodate >=0.5.4
    - rfc3986 >=1.1.0
    - tabulator >=1.20

test:
  imports:
    - tableschema
    - tableschema.constraints
    - tableschema.plugins
    - tableschema.types
  commands:
    - tableschema --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/tableschema-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A utility library for working with Table Schema in Python

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
